services:
  db:
    container_name: db_demo
    image: "postgres:16"
    environment:
      - POSTGRES_PASSWORD=Mydb123$
      - POSTGRES_USER=manasak
      - POSTGRES_DB=animalshelter
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5431:5432
  etl:
    container_name: etl_demo
    build: .
    depends_on:
    - db

volumes:
  db_data: